/**
 * Catálogo de seed (Anexos A e B do PRD). Extraído do seed para um módulo próprio
 * para poder ser verificado por teste de contrato (catalog.test.ts) sem rodar o seed.
 *
 * Fiel à TABELA do Anexo A: 26 marcas, 107 modelos. A linha "Totais: 27 marcas,
 * 106 modelos" do PRD está inconsistente com a própria tabela — a tabela é a fonte.
 */

// Anexo A. Willys → Jeep; Rural/F-75 → Ford; Shark → BYD; grafias normalizadas.
export const VEHICLE_CATALOG: Record<string, readonly string[]> = {
  Agrale: ['Marruá AM100', 'Marruá AM200'],
  BYD: ['Shark'],
  CBT: ['Javali'],
  Chevrolet: [
    'S10',
    'Trailblazer',
    'Blazer',
    'Tracker',
    'Equinox',
    'Silverado 1500',
    'Colorado',
    'D-20',
    'Bonanza',
    'Veraneio',
  ],
  Engesa: ['Engesa 4', 'Engesa 6'],
  Fiat: ['Toro', 'Titano'],
  Ford: [
    'Ranger',
    'Bronco',
    'Bronco Sport',
    'Maverick',
    'Explorer',
    'F-150',
    'F-250',
    'Rural',
    'F-75',
  ],
  Gurgel: ['X-12', 'Xavante', 'Carajás'],
  GWM: ['Haval H6', 'Tank 300', 'Tank 500', 'Poer P30'],
  Hyundai: ['Santa Fé', 'Tucson', 'Galloper'],
  Jeep: [
    'Willys',
    'Compass',
    'Renegade',
    'Commander',
    'Grand Cherokee',
    'Cherokee',
    'Cherokee Sport XJ',
    'Wrangler',
    'Gladiator',
  ],
  JPX: ['Montez'],
  KIA: ['Sorento', 'Mohave', 'Sportage'],
  Lada: ['Niva'],
  'Land Rover': [
    'Defender 90',
    'Defender 110',
    'Defender 130',
    'Discovery',
    'Discovery Sport',
    'Freelander',
  ],
  'Mercedes-Benz': ['GLB 200', 'Classe G', 'GLE'],
  Mitsubishi: [
    'L200 Triton',
    'Triton',
    'Triton Sport',
    'Pajero Full',
    'Pajero Dakar',
    'Pajero Sport',
    'Pajero TR4',
    'ASX',
    'Outlander',
    'Eclipse Cross',
  ],
  Nissan: ['Frontier', 'X-Terra', 'Pathfinder'],
  RAM: ['1500', '2500', '3500', 'Rampage', 'Dakota'],
  'Range Rover': ['Range Rover', 'Range Rover Sport', 'Evoque', 'Velar'],
  Renault: ['Duster', 'Oroch', 'Koleos'],
  Ssangyong: ['Actyon Sports', 'Korando', 'Rexton'],
  Suzuki: ['Jimny', 'Jimny Sierra', 'Jimny 4Sport', 'Vitara', 'Grand Vitara', 'SX4', 'Samurai'],
  Toyota: ['Hilux', 'SW4', 'Bandeirante', 'Land Cruiser', 'Land Cruiser Prado', 'RAV4'],
  Troller: ['T4', 'TX4', 'RF'],
  Volkswagen: ['Amarok', 'Tiguan', 'Touareg'],
};

// Anexo B — roteiros do catálogo. "Personalizado" é kind: custom (§3.5.1).
export const ITINERARIES: readonly string[] = [
  'Soldados Sebold',
  'Coxilha Rica',
  'Urubici 360',
  'Serra Gaúcha',
  'Pirâmides Sagradas',
  'Quatro Elementos',
  'Caminho Austral',
  'Terra de Gigantes',
  'Vale Europeu',
  'Rota das Cascatas',
  'Caminho das Montanhas',
  'Ametista e Missões',
  'Extremo Sul',
  'Farol de Santa Marta',
  'Personalizado',
];
